spring.application.name=GestionEstudiantes

spring.datasource.url=jdbc:postgresql://dpg-d5qj3m7gi27c73fe2ndg-a.virginia-postgres.render.com:5432/gestion_estudiantes
spring.datasource.username=gestion_user
spring.datasource.password=ANFQLGsWHMORaCQcre9yJGuQpkS5oH9v
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

server.port=8080
